import type { Teacher, TeacherStatusFilter } from './types';

export const teachers: Teacher[] = [
  {
    id: 'T-001',
    name: 'Linh Nguyễn',
    email: 'linh.n@lumen.edu',
    phone: '0901 234 567',
    initials: 'LN',
    tone: 'rose',
    subjects: ['Scratch', 'Python'],
    classCount: 5,
    studentCount: 62,
    rating: 4.9,
    status: 'active'
  },
  {
    id: 'T-002',
    name: 'Quang Vũ Phạm',
    email: 'quang.v@lumen.edu',
    phone: '0902 345 678',
    initials: 'QV',
    tone: 'sky',
    subjects: ['Python', 'JavaScript'],
    classCount: 4,
    studentCount: 48,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-003',
    name: 'Mai Hương Lê',
    email: 'mai.h@lumen.edu',
    phone: '0903 456 789',
    initials: 'MH',
    tone: 'violet',
    subjects: ['Web Design', 'UI/UX'],
    classCount: 3,
    studentCount: 32,
    rating: 4.7,
    status: 'active'
  },
  {
    id: 'T-004',
    name: 'Đức Anh Hoàng',
    email: 'duc.a@lumen.edu',
    phone: '0904 567 890',
    initials: 'DA',
    tone: 'amber',
    subjects: ['Robotics', 'Arduino', '+1'],
    classCount: 2,
    studentCount: 18,
    rating: 4.6,
    status: 'active'
  },
  {
    id: 'T-005',
    name: 'Thanh Tùng Vũ',
    email: 'tung.v@lumen.edu',
    phone: '0905 678 901',
    initials: 'TT',
    tone: 'emerald',
    subjects: ['Game Dev', 'Unity'],
    classCount: 3,
    studentCount: 36,
    rating: 4.9,
    status: 'on_leave'
  },
  {
    id: 'T-006',
    name: 'Hà Giang Trịnh',
    email: 'ha.g@lumen.edu',
    phone: '0906 789 012',
    initials: 'HG',
    tone: 'foreground',
    subjects: ['Math', 'Logic'],
    classCount: 4,
    studentCount: 52,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-007',
    name: 'Phương Thảo Bùi',
    email: 'thao.b@lumen.edu',
    phone: '0907 890 123',
    initials: 'PT',
    tone: 'rose',
    subjects: ['English', 'Creative Writing'],
    classCount: 2,
    studentCount: 22,
    rating: 5.0,
    status: 'pending'
  },
  {
    id: 'T-008',
    name: 'Minh Tuấn Đặng',
    email: 'minh.t@lumen.edu',
    phone: '0908 901 234',
    initials: 'MT',
    tone: 'sky',
    subjects: ['AI Explorers', 'Python'],
    classCount: 4,
    studentCount: 41,
    rating: 4.7,
    status: 'active'
  },
  {
    id: 'T-009',
    name: 'Ngọc Bích Trần',
    email: 'bich.t@lumen.edu',
    phone: '0909 012 345',
    initials: 'NB',
    tone: 'violet',
    subjects: ['Scratch', 'Game Dev'],
    classCount: 3,
    studentCount: 27,
    rating: 4.6,
    status: 'active'
  },
  {
    id: 'T-010',
    name: 'Hải Đăng Lý',
    email: 'dang.l@lumen.edu',
    phone: '0910 123 456',
    initials: 'HĐ',
    tone: 'amber',
    subjects: ['Robotics', 'Electronics'],
    classCount: 2,
    studentCount: 20,
    rating: 4.5,
    status: 'pending'
  },
  {
    id: 'T-011',
    name: 'Bảo Châu Nguyễn',
    email: 'chau.n@lumen.edu',
    phone: '0911 234 567',
    initials: 'BC',
    tone: 'emerald',
    subjects: ['Web Design', 'JavaScript'],
    classCount: 5,
    studentCount: 58,
    rating: 4.9,
    status: 'active'
  },
  {
    id: 'T-012',
    name: 'Khánh Linh Đỗ',
    email: 'khanh.l@lumen.edu',
    phone: '0912 345 678',
    initials: 'KL',
    tone: 'rose',
    subjects: ['English', 'Public Speaking'],
    classCount: 3,
    studentCount: 35,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-013',
    name: 'Trọng Nghĩa Phan',
    email: 'nghia.p@lumen.edu',
    phone: '0913 456 789',
    initials: 'TN',
    tone: 'foreground',
    subjects: ['Math', 'Physics'],
    classCount: 4,
    studentCount: 44,
    rating: 4.7,
    status: 'active'
  },
  {
    id: 'T-014',
    name: 'Hồng Nhung Vũ',
    email: 'nhung.v@lumen.edu',
    phone: '0914 567 890',
    initials: 'HN',
    tone: 'violet',
    subjects: ['UI/UX', 'Web Design'],
    classCount: 2,
    studentCount: 24,
    rating: 4.6,
    status: 'on_leave'
  },
  {
    id: 'T-015',
    name: 'Đăng Khoa Trương',
    email: 'khoa.t@lumen.edu',
    phone: '0915 678 901',
    initials: 'ĐK',
    tone: 'sky',
    subjects: ['Python', 'AI Explorers'],
    classCount: 5,
    studentCount: 60,
    rating: 4.9,
    status: 'active'
  },
  {
    id: 'T-016',
    name: 'Thùy Dương Lê',
    email: 'duong.l@lumen.edu',
    phone: '0916 789 012',
    initials: 'TD',
    tone: 'amber',
    subjects: ['Scratch', 'Creative Writing'],
    classCount: 3,
    studentCount: 30,
    rating: 4.7,
    status: 'active'
  },
  {
    id: 'T-017',
    name: 'Văn Hậu Phạm',
    email: 'hau.p@lumen.edu',
    phone: '0917 890 123',
    initials: 'VH',
    tone: 'emerald',
    subjects: ['Game Dev', 'Unity'],
    classCount: 4,
    studentCount: 46,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-018',
    name: 'Anh Thư Bùi',
    email: 'thu.b@lumen.edu',
    phone: '0918 901 234',
    initials: 'AT',
    tone: 'rose',
    subjects: ['English', 'Literature'],
    classCount: 2,
    studentCount: 26,
    rating: 4.6,
    status: 'pending'
  },
  {
    id: 'T-019',
    name: 'Quốc Bảo Hoàng',
    email: 'bao.h@lumen.edu',
    phone: '0919 012 345',
    initials: 'QB',
    tone: 'foreground',
    subjects: ['Robotics', 'Arduino'],
    classCount: 3,
    studentCount: 33,
    rating: 4.7,
    status: 'active'
  },
  {
    id: 'T-020',
    name: 'Yến Nhi Đặng',
    email: 'nhi.d@lumen.edu',
    phone: '0920 123 456',
    initials: 'YN',
    tone: 'violet',
    subjects: ['Web Design', 'CSS'],
    classCount: 4,
    studentCount: 42,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-021',
    name: 'Gia Hân Lý',
    email: 'han.l@lumen.edu',
    phone: '0921 234 567',
    initials: 'GH',
    tone: 'sky',
    subjects: ['Python', 'Data Science'],
    classCount: 5,
    studentCount: 55,
    rating: 4.9,
    status: 'active'
  },
  {
    id: 'T-022',
    name: 'Hữu Phước Trần',
    email: 'phuoc.t@lumen.edu',
    phone: '0922 345 678',
    initials: 'HP',
    tone: 'amber',
    subjects: ['Math', 'Logic'],
    classCount: 3,
    studentCount: 38,
    rating: 4.7,
    status: 'on_leave'
  },
  {
    id: 'T-023',
    name: 'Diệu Linh Nguyễn',
    email: 'linh.d@lumen.edu',
    phone: '0923 456 789',
    initials: 'DL',
    tone: 'emerald',
    subjects: ['Scratch', 'Game Dev'],
    classCount: 4,
    studentCount: 43,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-024',
    name: 'Tiến Dũng Phan',
    email: 'dung.p@lumen.edu',
    phone: '0924 567 890',
    initials: 'TD',
    tone: 'rose',
    subjects: ['JavaScript', 'React'],
    classCount: 5,
    studentCount: 59,
    rating: 4.9,
    status: 'active'
  },
  {
    id: 'T-025',
    name: 'Hương Giang Vũ',
    email: 'giang.v@lumen.edu',
    phone: '0925 678 901',
    initials: 'HG',
    tone: 'violet',
    subjects: ['UI/UX', 'Figma'],
    classCount: 2,
    studentCount: 23,
    rating: 4.6,
    status: 'pending'
  },
  {
    id: 'T-026',
    name: 'Anh Khoa Đỗ',
    email: 'khoa.d@lumen.edu',
    phone: '0926 789 012',
    initials: 'AK',
    tone: 'sky',
    subjects: ['Robotics', 'Electronics'],
    classCount: 4,
    studentCount: 40,
    rating: 4.7,
    status: 'active'
  },
  {
    id: 'T-027',
    name: 'Thanh Hằng Lê',
    email: 'hang.l@lumen.edu',
    phone: '0927 890 123',
    initials: 'TH',
    tone: 'amber',
    subjects: ['English', 'Creative Writing'],
    classCount: 3,
    studentCount: 31,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-028',
    name: 'Minh Khôi Trương',
    email: 'khoi.t@lumen.edu',
    phone: '0928 901 234',
    initials: 'MK',
    tone: 'emerald',
    subjects: ['AI Explorers', 'Python'],
    classCount: 5,
    studentCount: 54,
    rating: 4.9,
    status: 'active'
  },
  {
    id: 'T-029',
    name: 'Phương Anh Bùi',
    email: 'anh.b@lumen.edu',
    phone: '0929 012 345',
    initials: 'PA',
    tone: 'rose',
    subjects: ['Web Design', 'JavaScript'],
    classCount: 3,
    studentCount: 34,
    rating: 4.7,
    status: 'on_leave'
  },
  {
    id: 'T-030',
    name: 'Hoàng Long Phạm',
    email: 'long.p@lumen.edu',
    phone: '0930 123 456',
    initials: 'HL',
    tone: 'foreground',
    subjects: ['Math', 'Physics'],
    classCount: 4,
    studentCount: 45,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-031',
    name: 'Khả Hân Hoàng',
    email: 'han.h@lumen.edu',
    phone: '0931 234 567',
    initials: 'KH',
    tone: 'violet',
    subjects: ['Scratch', 'Animation'],
    classCount: 2,
    studentCount: 25,
    rating: 4.6,
    status: 'pending'
  },
  {
    id: 'T-032',
    name: 'Sơn Tùng Đặng',
    email: 'son.d@lumen.edu',
    phone: '0932 345 678',
    initials: 'ST',
    tone: 'sky',
    subjects: ['Game Dev', 'Unity', 'C#'],
    classCount: 5,
    studentCount: 57,
    rating: 4.9,
    status: 'active'
  },
  {
    id: 'T-033',
    name: 'Mỹ Linh Nguyễn',
    email: 'mylinh.n@lumen.edu',
    phone: '0933 456 789',
    initials: 'ML',
    tone: 'amber',
    subjects: ['English', 'IELTS'],
    classCount: 4,
    studentCount: 47,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-034',
    name: 'Văn Toàn Lý',
    email: 'toan.l@lumen.edu',
    phone: '0934 567 890',
    initials: 'VT',
    tone: 'emerald',
    subjects: ['Robotics', 'Arduino'],
    classCount: 3,
    studentCount: 29,
    rating: 4.7,
    status: 'active'
  },
  {
    id: 'T-035',
    name: 'Trà My Trần',
    email: 'my.t@lumen.edu',
    phone: '0935 678 901',
    initials: 'TM',
    tone: 'rose',
    subjects: ['UI/UX', 'Web Design'],
    classCount: 4,
    studentCount: 39,
    rating: 4.8,
    status: 'active'
  },
  {
    id: 'T-036',
    name: 'Nhật Minh Vũ',
    email: 'nhatminh.v@lumen.edu',
    phone: '0936 789 012',
    initials: 'NM',
    tone: 'foreground',
    subjects: ['Python', 'Data Science'],
    classCount: 5,
    studentCount: 50,
    rating: 4.9,
    status: 'active'
  },
  {
    id: 'T-037',
    name: 'Lan Anh Phan',
    email: 'lan.p@lumen.edu',
    phone: '0937 890 123',
    initials: 'LA',
    tone: 'violet',
    subjects: ['Creative Writing', 'Literature'],
    classCount: 2,
    studentCount: 21,
    rating: 4.6,
    status: 'pending'
  }
];

export const teacherStatusTabConfig: { value: TeacherStatusFilter }[] = [
  { value: 'all' },
  { value: 'active' },
  { value: 'on_leave' },
  { value: 'pending' }
];
